### ISSUE TITLE
Extracting tweets through Flume

### ISSUE THREAD

**Issue by sudarshan395** [RealyUniqueName/haxe#17]
i am tryiing to extract twitter data through flume and getting this error

2016-08-13 17:21:12,945 (conf-file-poller-0) [ERROR - org.apache.flume.node.Poll                                                                                        ingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingProperties                                                                                        FileConfigurationProvider.java:149)] Unhandled error
java.lang.AssertionError: java.lang.reflect.InvocationTargetException
        at twitter4j.HttpClientFactory.getInstance(HttpClientFactory.java:81)
        at twitter4j.TwitterStreamImpl.<init>(TwitterStreamImpl.java:51)
        at twitter4j.TwitterStreamFactory.<clinit>(TwitterStreamFactory.java:40)
        at org.apache.flume.source.twitter.TwitterSource.configure(TwitterSource                                                                                        .java:115)
        at org.apache.flume.conf.Configurables.configure(Configurables.java:41)
        at org.apache.flume.node.AbstractConfigurationProvider.loadSources(Abstr                                                                                        actConfigurationProvider.java:326)
        at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(                                                                                        AbstractConfigurationProvider.java:97)
        at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$File                                                                                        WatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                        1)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                        access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.                                                                                        run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                        java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                        .java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct                                                                                        orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC                                                                                        onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at twitter4j.HttpClientFactory.getInstance(HttpClientFactory.java:73)
        ... 14 more
Caused by: java.lang.NoSuchMethodError: twitter4j.conf.Configuration.getHttpClie                                                                                        ntConfiguration()Ltwitter4j/HttpClientConfiguration;
        at twitter4j.StreamingReadTimeoutConfiguration.isGZIPEnabled(TwitterStre                                                                                        amImpl.java:804)
        at twitter4j.HttpClientBase.<init>(HttpClientBase.java:25)
        at twitter4j.HttpClientImpl.<init>(HttpClientImpl.java:55)
        ... 19 more

**Comment by RealyUniqueName** [comment]
How did you reach this place? )

**Comment by sudarshan395** [comment]
What do u mean?

**Comment by RealyUniqueName** [comment]
I mean how is your issue related to Haxe?
